name: appsmith-cd  # Workflow name

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  deploy-appsmith:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      - run: "curl --location --fail-early --request POST https://smartforce.demo.appsmith.com/api/v1/git/applications/696e7c12f5c31a2d63a55e60/deploy?refName=master --header 'Authorization: ${{ secrets.APPSMITH_CD_KEY }}'"
